version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: doc/conf.py


build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: environment.yml

formats: all
