version: 2

jobs:
  runtests:
  
    macos:
      xcode: "9.0"
    
    environment:
      PYTEST_QT_API: pyqt5
      PYTHON_VERSION: 3.6
      
    steps:
      - checkout
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install wget
      - run: cd && rm -rf ~/.pyenv && rm -rf ~/virtualenvs
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh
      - run: chmod +x ~/miniconda.sh && ~/miniconda.sh -b
      - run: echo "export PATH=~/miniconda3/bin:$PATH" >> $BASH_ENV
      - run: conda config --set always_yes yes
      - run: conda create --quiet --name cqtest -c cadquery -c conda-forge pythonocc-core=0.18.2 oce=0.18.2 python=$PYTHON_VERSION pyparsing mock lldb
      - run: |
          source activate cqtest
          pip install coverage
          python setup.py install
          conda env list
          conda list
          coverage run runtests.py
      
workflows:
  version: 2
  
  workflow:
    jobs:
    - runtests