package:
  name: cadquery
  version:  {{ environ.get('PACKAGE_VERSION') }}

source:
  path: ..

build:
  string: {{ 'py'+environ.get('PYTHON_VERSION')}}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python {{ environ.get('PYTHON_VERSION') }}
    - setuptools
  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - ocp 7.7.*
    - pyparsing >=2.1.9
    - ezdxf
    - ipython
    - typing_extensions
    - nptyping 2.0.1
    - nlopt
    - multimethod >=1.7,<2.0
    - casadi

test:
  requires:
    - pytest
    - docutils
    - path
  source_files:
    - tests/
  commands:
    - pytest -v

about:
  summary: CadQuery - scripted CAD based on OCCT
