package:
  name: cadquery-occ
  version:  {{ environ.get('TRAVIS_TAG') }}

source: 
  path: ..

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - string: {{ environ.get('TRAVIS_COMMIT') }}
    - python {{ environ.get('TRAVIS_PYTHON_VERSION') }}
    - setuptools
  run:
    - python {{ environ.get('TRAVIS_PYTHON_VERSION') }}
    - oce 0.18.1
    - pythonocc-core 0.18
    - pyparsing 2.1.4

about:
  summary: Experimental CadQuery fork based on PythonOCC