package:
  name: cadquery
  version:  {{ environ.get('PACKAGE_VERSION') }}

source:
  path: ..

build:
  string: {{ 'py'+environ.get('PYTHON_VERSION')}}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python {{ environ.get('PYTHON_VERSION') }}
    - setuptools
  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - oce 0.18.*
    - pythonocc-core 0.18.2*
    - pyparsing 2.*
    - ezdxf
    
test:
  requires:
    - pytest	
  source_files:
    - tests/
  commands:
    - pytest -v

about:
  summary: CadQuery fork based on PythonOCC
