package:
  name: cadquery
  version:  {{ environ.get('PACKAGE_VERSION') }}

source:
  path: ..

build:
  string: {{ 'py'+environ.get('PYTHON_VERSION')}}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python {{ environ.get('PYTHON_VERSION') }}
    - setuptools
  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - ocp 7.5.2
    - hdf5 1.10.6 *1114
    - pyparsing >=2.1.9
    - ezdxf
    - ipython
    - typing_extensions
    - nptyping
    - nlopt
    - multimethod 1.6

test:
  requires:
    - pytest
    - docutils
    - path
  source_files:
    - tests/
  commands:
    - LD_DEBUG=libs python -c"import OCP"
    - pytest -v

about:
  summary: CadQuery - scripted CAD based on OCCT
