FROM mambaorg/micromamba:latest

COPY --chown=$MAMBA_USER:$MAMBA_USER environment.yml /tmp/environment.yml
COPY --chown=$MAMBA_USER:$MAMBA_USER ./ /tmp/cq

RUN micromamba install -y -q -n base git && \
    head -n -1 /tmp/environment.yml  > /tmp/environment_.yml && \
    micromamba install -y -q -n base -f /tmp/environment_.yml && \
    micromamba run pip install -e /tmp/cq && \
    micromamba list && \
    micromamba clean --all --yes

ARG MAMBA_DOCKERFILE_ACTIVATE=1  # (otherwise python will not be found)

