FROM mambaorg/micromamba:latest

COPY --chown=$MAMBA_USER:$MAMBA_USER environment.yml /opt/environment.yml
COPY --chown=$MAMBA_USER:$MAMBA_USER ./ /opt/cq

USER root
RUN chown -R $MAMBA_USER:$MAMBA_USER /opt 

USER $MAMBA_USER
RUN micromamba install -y -q -n base git && \
    head -n -1 /opt/environment.yml  > /opt/environment_.yml && \
    micromamba install -y -q -n base -f /opt/environment_.yml && \
    micromamba run pip install -e /opt/cq && \
    micromamba list && \
    micromamba clean --all --yes

ARG MAMBA_DOCKERFILE_ACTIVATE=1  # (otherwise python will not be found)

